---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: slinguer-ci-cd
    dev_namespace: slinguer-dev
    test_namespace: slinguer-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
